/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Monday;
import javax.swing.*;
public class App {
    
    public static void main(String[] args) {
        String[] Animals = new String[10];
         String Animal;
         
         for (int i = 0; i<Animals.length; i++)
         {
             
             Animal = JOptionPane.showInputDialog("Please enter Animal");
              Animals[i] = Animal;
              
         }
        JOptionPane.showMessageDialog(null, Animals);
    }
}
